language: ruby
rvm:
- 2.1.1
install:
- bundle install
branches:
  only:
  - develop
script:
- bundle exec rake deploy
notifications:
  email: false
env:
  global:
    secure: IjhSBnLzZCUFWKSs7X6yZ6cjvgMYdCkXPgm+x+aFGvv0L63Wzy4e3P6o3XUUCmAK8F4vduEyqhTbwmCad36hfMH4KJi52jKc27YBXKWze/I7v9lTFVrkltoIAcjjfAAwFWvtdbXXwkvSoiejU9LUeEU905umZTdxKyj5CYThRxIO93ywRyKyVeEGbVblluqg0glGEqiYYbSq7NqOQzJIniNLg0OoID2sRV0pQ35GDGNdWHOlkn6dMZ34W/bhnAfNxIf+i8+nTscA1AnziM23VuOWXxaUxFWMD7Vf7AfuC06hJu0uA0LtU10BfAB0obfwkXkTjIhpWGD0tSwYxF0yBtAK3kF77cm1CeHG9TSNFAnXrpCq8ShksCLOrWO6mdvDTuZI3zHAeU0L+qFmEK9J98oQD76rkroZbWlvvaeye/v1BKkrJ50fKxjjk3wjE9DMSVaTwySp1YNuSKf9wLBl5ldmDdiXkbOrsM5u9D+zuoGCMInsfvhN6j4p7Tkea0I6uHSCU3wlNy99FmNf29P//9ZY4kNntLCtnux7lopjfey89fa8PRmCAoaiLs3OrXVrrCq373h7V6IuRsEmdzyEQ9Hnw+ar7yaf9ZOpJv6W4LaRe0LdqvMOcXtyXxmDRmNkDJbU5mOA8zL0aqN9/a6+LZFel/eBsn/nxw/K3YWNFIA=
