language: ruby
rvm:
- 2.6.0
before_install:
- git config --global user.email "vasilescu@gmail.com"
- git config --global user.name "Bogdan Vasilescu"
install:
- bundle install
branches:
  only:
  - develop
script:
- bundle exec rake deploy
notifications:
  email: false
env:
  global:
  - secure: QyBDvCwRfWTeul3n4E6uefSxQahO19EF0nxB0u85yHIGhhIorhbYOOkvA7kKBL6HIV0WmBLPM19kAWx2FDOztWuTw5vFAWbOT665YL98gTN7KFaTA6tBwc7i2/TRJ/KCuvbzEtru14UF8WRV4yN3nZZG5xKYORJxABP6UftflEOIvpjDuMg8NlcnoXkGgv2FrnGdW7MyfG43BE32jaBAcaNSqAKwJ4VuJYsv3hoH2p3WnKXC1Smhke8/eDM07icBBPN+YSpOuvYdwN6NX6IVA7pPl2S3qOEX6crhf+a5T8mRyLeF3cuMAqSl6c14cdY67I4XIsNoiO19z6VO8ExEsw4+jkCFcQTCh5kwUEmcHzHMQR0f1dLJ+uVuouDRo0EbSuZrrN+NtXpdfEgwWD5wttGf7HptZQvcBXaavMYllP49J/rjC6CIYI95EE14cFJyiFS8OlSCRJcyAAQZWjfqMmyWSPEp69c20icQ49rMqh9XRWdlkx7bmQCbb7BkpDlojOArCMGBpjOPYH+fqmA3/NpB7VFCcxSxRwjiyBJq1Cc1iX760T+4tm5PELzpVHDdH4qrM6+NEH+depMcHBDSKCOl6EoPibd2eeqSi8R1RujBg5Ll+kmOEgI/5J68H2oY0A96enuW0aKoo+pfN6++1pbfYHKx0R97tqQz6+sqwGc=
