language: ruby
rvm:
- 2.1.1
install:
- bundle install
branches:
  only:
  - develop
script:
- bundle exec rake deploy
notifications:
  email: false
env:
  global:
#  - secure: H/aEZo0fy/NGn9p5c69TbpoieQFfdhNZtg8WTkSwu+sNRoBxX9TxnKBcqYlNKw9+Tt13+9/Xi1cmo0Geg6ZZOVpqwgxijIMu3vnBRtnlDTPIBQEqoHBOpYdsQJUnUyL6f6XA/Pxeze/twVkRRM3+x64rACXwvdsV+G0rLyEjYp9ImEa9ynojCg9qHqfURrM5wF/VXA8E3yCegLXQNxXYkVCxVX4rOaL0XdtLFU23gyhPjbR8SyicI+KFVn/5aBIR+90XjT43nLdeqOboIJo47LVlBosXh18gaS4o9DzYkn8iF0/Hp6IXUi/w45gXwp91Eb98GV7IjsRlf8ycrB6380kkOcWlCgNGsHtnYcyFgWc/FrkHfbOAaDsKM8QHrvAWAlC7a1kbtuZ153IcaLArfydxIaSVfXWz4uu9Ys4htUwZPbM+NARUhqJL0UgDUidrvc6yt5di46ZczK9ntA4+kSVFRGBaReiP52ETm5gtPrlyY9J7NdEqDOVxpFX0V5pK4BgH07Pd2G5oySJELIBJnp+9OLbzsyV9PwOknZ21Bvohbay6CKQrK0bGcWPFot6zad1mf3sRlxTMNDqbis7GVlVhgvN3i3PdLKDgh051Eq4xPO628Ve4EuBAqbFalMf5nTG4jF4TRxLEr7QYZeMxLVKzQw7wKIYxPNNOjr2txq0=
  - secure: LPL8MRGMJYmQGA8waf5GKgiD8gl5aAZHqgeIB0YUx4KF/38PLFBY4DaO8oCuSAc/oLu1/cDyccujrozcBGT0GymG4F11GcA5SxDZMhV7XGaNRncNDfTBxahEzpt01lsw9hKzRoIKl7rIPPxiqsmujC5E+kYbagn5spsI4tIysb0zdePmwYkutx1x4LI3HzV1fowkFRH7EofeHG2LAWi51k1tCvUIFQVD6upFqqYEpdWL7faealBOGwymZeepQOihwBX8mmN2xs47RoX/rwCuh0xwOYb6LsLuwDaa3nPYUnfhvN/gAR5gLnKYCfUSGsjiDLpvFl470wt3GEBFWO4/8r8IpfbEGwihglCZh+6f2mhFUOCv7eWn2PDLEjimYlO+lj1Vgalg6c2HuMcGnLDI+ci0TeUC6hSlQxSXe/p19UWJ7fcQS9E4ryQFWQJ0zYGHlXUNjdj5RVQvLmmgHrjYDTUzsh9X5RRsotUdaz0rSfAHmVekgaYkLLvHZpnQKvGGqQCvCehy7/1Tfoh03mxL4QmHS/E9JDWGSI48W/nYO5gJXzfCaVMpGNgef38OTHxcBPiacMyoTV618Fdg5zGiYoHZPTGBau/Tm1PecZDU4VRaF/FwGdROlxytHLd23zxB1ip3KiBKujqRVo0r3nnvudOtSItUvW5oR3ux01O1H4c=
