# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bogdan Vasilescu
tagline:          'Welcome to my website!'
baseurl:          /

paginate:         5

# Custom vars
scholar:
  style: assets/my-acm-sigchi-proceedings.csl
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  

safe: false
lsi: false
pygments: true

#relative_source: ../EXAMPLE/
#destination: ../_site/ #../EXAMPLE/
#
# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: bvasiles
repo: bvasiles.github.io
branch: develop

#permalink: pretty
#
#paginate: 10
#paginate_path: "blog/page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
#  - .travis.yml

